version: "3.9"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules